name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ts-tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-ts

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run tests
      run: yarn test